kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: rust:1.87.0
    commands:
      - cargo build
  - name: leptos build
    image: rust:1.87.0
    commands:
      - cargo install trunk
      - cargo install --locked cargo-leptos
      - rustup target add wasm32-unknown-unknown
      - cargo leptos build
  - name: test
    image: rust:1.87.0
    commands:
      - cargo check
  - name: lint
    image: rust:1.87.0
    commands:
      - rustup component add clippy
      - cargo clippy --all-targets --all-features -- -D warnings

trigger:
  event:
    - cron
    - custom
    - push
