[workspace]
resolver = "2"
members = ["api", "app", "domain", "server"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85.1"

[profile.dev]
opt-level = 0
debug = 0

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'

[workspace.dependencies]
quench-web = { version = "0.1.11", registry = "ennor" }

actix-files = "0.6.10"
actix-web = { version = "4.14", features = ["rustls-0_23"] }
actix-ws = "0.3.1"
quench-auth = { version = "0.3.5", registry = "ennor" }
quench-cache = { version = "0.1.6", registry = "ennor", features = ["redis"] }
quench-starter = { version = "0.3.4", registry = "ennor" }
uuid = { version = "1.24", features = ["v4"] }
anyhow = "1"
base64 = "0.22"
chrono = "0.4"
futures = "0.3"
log = "0.4"
native-tls = "0.2"
regex = "1.11"
reqwest = { version = "0.12", features = ["json", "stream"] }
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.9"
tokio = { version = "1.33", features = ["full"] }
tokio-tungstenite = { version = "0.26", features = ["native-tls"] }
url = "2.5"
openssl = "0.10.72"
