[package]
name = "app"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
api = { path = "../api" }
base64.workspace = true
chrono.workspace = true
domain = { path = "../domain" }
quench-auth.workspace = true
quench-cache.workspace = true
quench-web.workspace = true
regex.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
