[package]
name = "api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
domain = { path = "../domain" }

leptos.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
