[package]
name = "api"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
domain = { path = "../domain" }

anyhow.workspace = true
quench-auth.workspace = true
quench-cache.workspace = true
quench-config = { version = "0.1.2", registry = "ennor" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
